AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  jpegger

  Sample SAM Template for jpegger

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 512
    Runtime: nodejs22.x
    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
    Cors:
      AllowMethods: "'GET,POST,PUT,OPTIONS'"
      AllowHeaders: "'Content-Type,Authorization'"
      AllowOrigin: "'*'"

Metadata:
  BuildMethod: esbuild

Parameters:
  Env:
    Type: String
    Default: dev
  UserPoolAdminGroupName:
    Description: Group name for  administrators
    Type: String
    Default: 'AdminGroup'
  AuthCallbackUrl:
    Type: String
    Description: Auth callback in production
    Default: 'https://main.d2cb8nb37vaa0c.amplifyapp.com'
  AuthCallbackUrlLocal:
    Type: String
    Description: Auth callback in production
    Default: 'http://localhost:3000'
  PrimaryRegion:
    Type: String
    Default: "eu-central-1"
  DRRegion:
    Type: String
    Default: "eu-west-1"

Conditions:
  IsPrimaryRegion: !Equals [ !Ref AWS::Region, !Ref PrimaryRegion ]
  IsDRRegion: !Not [ !Condition IsPrimaryRegion ]

Resources:
  NodeModulesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: NodeModules
      Description: Contains node_modules for Lambda functions
      ContentUri: lambda-layers/
      CompatibleRuntimes:
        - nodejs22.x

  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Layers:
        - !Ref NodeModulesLayer
      CodeUri: src/
      Handler: authorizer.handler
      Runtime: nodejs22.x
      Description: Handler for Lambda authorizer
      Environment:
        Variables:
          USER_POOL_ID: !Ref UserPool
          APP_CLIENT_ID: !Ref UserPoolClient
          ADMIN_GROUP_NAME: !Ref UserPoolAdminGroupName
      Tags:
        Stack: !Sub "${AWS::StackName}"


  AccessLogs:
    Type: AWS::Logs::LogGroup
    DependsOn: ApiLoggingRole
    Properties:
      RetentionInDays: 30
      LogGroupName: !Sub "/${AWS::StackName}/APIAccessLogs"

  ApiLoggingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action: "sts:AssumeRole"
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs

  ApiGatewayAccountLoggingSettings:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt ApiLoggingRole.Arn

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${AWS::StackName}-UserPool
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: true
      UsernameAttributes:
        - email
      UserPoolTags:
        Key: Name
        Value: !Sub ${AWS::StackName} User Pool
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
#          RequireNumbers: true
#          RequireSymbols: true
          TemporaryPasswordValidityDays: 7

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName:
        !Sub ${AWS::StackName}-UserPoolClient
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: false
      PreventUserExistenceErrors: ENABLED
      RefreshTokenValidity: 30
      AccessTokenValidity: 6
      IdTokenValidity: 6
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days
      SupportedIdentityProviders:
        - COGNITO
      UserPoolId: !Ref UserPool
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - 'code'
        - 'implicit'
      AllowedOAuthScopes:
        - 'email'
        - 'openid'
        - 'aws.cognito.signin.user.admin'
      CallbackURLs:
        - !Ref AuthCallbackUrl
        - !Ref AuthCallbackUrlLocal

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Ref UserPoolClient
      UserPoolId: !Ref UserPool

  # DynamoDB Table
  ImagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Images
      AttributeDefinitions:
        - AttributeName: UserId
          AttributeType: S
        - AttributeName: ImageId
          AttributeType: S
      KeySchema:
        - AttributeName: UserId
          KeyType: HASH
        - AttributeName: ImageId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  StagingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-staging-bucket'
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  PrimaryBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-primary-bucket'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      VersioningConfiguration:
        Status: Enabled
      ReplicationConfiguration: !If
        - IsPrimaryRegion
        - Role: !GetAtt S3ReplicationRole.Arn
          Rules:
            - Destination:
                Bucket: !Sub 'arn:aws:s3:::${AWS::StackName}-bucket-bin'
              Status: Enabled
              Prefix: ""
        - !Ref 'AWS::NoValue'

  BucketBin:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-bucket-bin'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      VersioningConfiguration:
        Status: Enabled

  S3ReplicationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3ReplicationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ReplicateObject
                  - s3:ReplicateDelete
                  - s3:ReplicateTags
                  - s3:GetObjectVersionForReplication
                  - s3:GetBucketVersioning
                  - s3:GetBucketLocation
                Resource:
                  - !If
                    - IsPrimaryRegion
                    - !Sub 'arn:aws:s3:::${AWS::StackName}-primary-bucket'
                    - !Ref 'AWS::NoValue'
                  - !If
                    - IsPrimaryRegion
                    - !Sub 'arn:aws:s3:::${AWS::StackName}-primary-bucket/*'
                    - !Ref 'AWS::NoValue'
                  - !If
                    - IsDRRegion
                    - !Sub 'arn:aws:s3:::${AWS::StackName}-bucket-bin'
                    - !Ref 'AWS::NoValue'
                  - !If
                    - IsDRRegion
                    - !Sub 'arn:aws:s3:::${AWS::StackName}-bucket-bin/*'
                    - !Ref 'AWS::NoValue'

  ImageUploadHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/image-upload.handler
      Policies:
        - S3WritePolicy:
            BucketName: !Ref StagingBucket
        - DynamoDBWritePolicy:
            TableName: !Ref ImagesTable
      Events:
        UploadImageApi:
          Type: Api
          Properties:
            Path: /upload
            Method: post
      Environment:
        Variables:
          TABLE_NAME: !Ref ImagesTable
          STAGING_BUCKET: !Ref StagingBucket

  FetchAllImagesHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/all-images.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ImagesTable
        - S3ReadPolicy:
            BucketName: !Ref StagingBucket
      Environment:
        Variables:
          TABLE_NAME: !Ref ImagesTable
          STAGING_BUCKET: !Ref StagingBucket
      Events:
        FetchAllImagesApi:
          Type: Api
          Properties:
            Path: /images
            Method: GET

  RestAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      AuthorizerUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AuthorizerFunction.Arn}/invocations"
      IdentitySource: method.request.header.Authorization
      Name: CustomTokenAuthorizer
      RestApiId: !Sub ${ServerlessRestApi}
      Type: TOKEN

Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn
  StagingBucketName:
    Value: !Ref StagingBucket
  PrimaryBucketName:
    Value: !Ref PrimaryBucket
  ImagesTableName:
    Value: !Ref ImagesTable
  UserPoolId:
    Value: !Ref UserPool
  UserPoolClientId:
    Value: !Ref UserPoolClient
